version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"


# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
