name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  # - joblib
  # - tqdm
  # - pillow
  # - sphinx-gallery
  # - numpydoc
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  # - networkx
  # - pybind11
  # - loky
  - hdbscan
  - numba
  - jupyterlab
  # - jupytext
  # - jupyterlab-git
  # - pyqt=5.12.3
  # - pyqtgraph=0.12.4
  - pip:
    - neo
    - spikeinterface[full,widgets] 
    # @ git+https://github.com/SpikeInterface/spikeinterface.git
    - probeinterface
    - spikeinterface-gui
    # Uncomment either lines - not both - if using Docker or Singularity containers. 
    # - docker
    - spython
    - pynwb



