name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy==1.21
  - joblib==1.1
  - tqdm
  - pillow
  - sphinx-gallery
  - numpydoc
  - matplotlib
  - h5py
  - pandas
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - hdbscan
  - numba
  - jupyterlab
  - jupytext
  - jupyterlab-git
  - pyqt=5.12.3
  - pyqtgraph=0.12.4
  - pip:
    - neo>=0.11
    - spikeinterface[full,widgets] @ git+https://github.com/SpikeInterface/spikeinterface.git
    - probeinterface>=0.2.10
    - spikeinterface-gui>=0.4.1
    - tridesclous>=1.6.5
    - phy==2.0b5
    # Uncomment either lines - not both - if using Docker or Singularity containers. 
    # - docker
    # - spython
    - pynwb
    - figurl-jupyter


