name: Deploy Containers

on:
    workflow_dispatch:
    push:
        tags:
            - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build all containers
      run: ./environment/build_all.sh

    - name: Push all containers
      run: ./environment/push_all.sh