name: Test Nextflow Pipeline

on:
  pull_request:
      branches: [main]
      types: [synchronize, opened, reopened]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        
        - name: Free up disk space
          run: |
            echo "Before cleanup:"
            df -h
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/hostedtoolcache
            echo "After cleanup:"
            df -h

        - name: Install packages
          run: |
            python -m pip install --upgrade pip
            pip install spikeinterface neuroconv pynwb

        - name: Generate test NWB files
          run: |
            python sample_dataset/create_test_nwb.py
        
        - name: Set up Nextflow
          uses: nf-core/setup-nextflow@v1
          with:
            version: latest-stable

        - name: Run Nextflow pipeline
          run: |
            DATA_PATH="$(pwd)/sample_dataset/nwb" RESULTS_PATH="$(pwd)/sample_dataset/nwb/results" \
            nextflow  -C "$(pwd)/.github/workflows/nextflow_test.config" run pipeline/main_multi_backend.nf \
            --params_file "$(pwd)/.github/workflows/params_test.json"